Usage

git remote
List the remote connections you have to other repositories.

git remote -v
Same as the above command, but include the URL of each connection.

git remote add <name> <url>
Create a new connection to a remote repository. After adding a remote, you’ll be able to use <name> as a convenient shortcut for <url> in other Git commands.

git remote rm <name>
Remove the connection to the remote repository called 